CREATE TABLE IF NOT EXISTS category (
    id TEXT NOT NULL PRIMARY KEY,
    companyId TEXT NOT NULL,
    name TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL,
    createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deletedAt TEXT NULL
);
