CREATE TABLE IF NOT EXISTS `user` (
    `id` CHAR(36) NOT NULL PRIMARY KEY,
    `username` VARCHAR(255) NOT NULL UNIQUE,
    `email` VARCHAR(255) UNIQUE,
    `phone` VARCHAR(20),
    `password` VARCHAR(255) NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `refresh_token` (
    `id` CHAR(36) NOT NULL PRIMARY KEY,
    `userId` CHAR(36) NOT NULL,
    `token` VARCHAR(512) NOT NULL UNIQUE,
    `expiresAt` TIMESTAMP NOT NULL,
    `revokedAt` TIMESTAMP NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`userId`) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS `password_reset_token` (
    `id` CHAR(36) NOT NULL PRIMARY KEY,
    `userId` CHAR(36) NOT NULL,
    `token` VARCHAR(512) NOT NULL UNIQUE,
    `expiresAt` TIMESTAMP NOT NULL,
    `usedAt` TIMESTAMP NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`userId`) REFERENCES user(id)
);

